# TODO Needs updating - check args-test for latest
OLD_POTHOS = 4
CUBAN_OREGANO_AMBOINICUS = 3
ECHEVERIA = 2
NEW_POTHOS = 1
CURIO_FICOIDES = 0

"""
SMALL_SUCCULENTS = 0
LARGE_SUCCULENTS = 1 # CURIO_FICOIDES is the large spikey one from HMB shop
HERBS = 2
POTHOS_1 = 3 # OLDER MORE ESTABLISHED
POTHOS_2 = 4 # NEWER CUTTING

"""
